name: ci
on: [push]

jobs:

  check_mturk_changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: check for mturk changes
        id: check_files
        run: |
          echo "========== check paths of modified files =========="
          git diff --name-only HEAD^ HEAD > files.txt
          while IFS= read -r file
          do
            echo $file
            if [[ $file == *mturk.py ]]; then
              echo "This modified file is MTurk related."
              echo "::set-output name=mturk_changed::true"
              break
            else
              echo "This modified file is not MTurk related."
              echo "::set-output name=mturk_changed::false"
            fi
          done < files.txt

  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: pre-commit/action@v2.0.0
