name: Release
on: 
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    environment: pypi
    steps:
      - uses: actions/checkout@v2
      - name: Install Ubuntu packages
        run: sudo apt-get --yes install curl enchant pandoc
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6
      - name: Ruby dependencies
        run: |
          gem install danger
          gem install danger-commit_lint
          gem install chandler -v 0.7.0
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '10'
      - name: Install node packages
        run: yarn --frozen-lockfile --ignore-engines
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Python Installers
        run: pip install --upgrade pip wheel tox
      - name: Run danger (Ruby)
        run: bundle exec danger
      - name: Set up deployment
        env:
          CHANDLER_GITHUB_API_TOKEN: ${{ secrets.CHANDLER_GITHUB_API_TOKEN }}
        run: |
          pandoc --from=markdown --to=rst --output=README.rst README.md
          pip install build
          python -m build --sdist --wheel .
          chandler push --tag-prefix=v
      - name: Deploy
        uses: pypa/gh-action-pypi-publish@v1.4.2
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
